# Generated by Django 6.1.1 on 2026-09-07 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_from', models.CharField(max_length=120)),
                ('city_to', models.CharField(max_length=120)),
                ('brand', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=80)),
                ('color', models.CharField(max_length=60)),
                ('registration_number', models.CharField(max_length=40)),
                ('owner_name', models.CharField(max_length=120)),
                ('owner_phones', models.JSONField(default=list)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Остановка', 'Остановка'), ('Склад', 'Склад')], default='Остановка', max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=255)),
                ('maps_url', models.URLField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('address_delivery_available', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['country', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RewardSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('promocode', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('completed', 'Завершён'), ('planned', 'Запланирован')], default='planned', max_length=20)),
                ('route_variant', models.CharField(blank=True, max_length=40)),
                ('route_label', models.CharField(blank=True, max_length=255)),
                ('car_name', models.CharField(blank=True, max_length=120)),
                ('car_color', models.CharField(blank=True, max_length=60)),
                ('drivers', models.JSONField(blank=True, default=list, help_text='List of driver names')),
                ('start_city', models.CharField(max_length=120)),
                ('end_city', models.CharField(max_length=120)),
                ('departure_city', models.CharField(choices=[('odesa', 'Одесса'), ('kyiv', 'Киев')], default='odesa', max_length=20)),
                ('free_seats', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('applied_count', models.PositiveSmallIntegerField(default=0)),
                ('is_full', models.BooleanField(default=False)),
                ('package_capacity_kg', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=120)),
                ('time', models.CharField(help_text='Display string, e.g. "Чт 27.08 10:40"', max_length=60)),
                ('is_key_stop', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='core.trip')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PassengerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_label', models.CharField(blank=True, help_text='Free-text fallback if trip FK is unset', max_length=255)),
                ('city_from', models.CharField(max_length=120)),
                ('address_from', models.CharField(blank=True, max_length=255)),
                ('city_to', models.CharField(max_length=120)),
                ('address_to', models.CharField(blank=True, max_length=255)),
                ('full_name', models.CharField(max_length=120)),
                ('phones', models.JSONField(default=list)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('promocode', models.CharField(blank=True, max_length=40)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passenger_applications', to='core.trip')),
            ],
        ),
        migrations.CreateModel(
            name='PackageApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_label', models.CharField(blank=True, max_length=255)),
                ('place', models.PositiveSmallIntegerField(default=1)),
                ('weight_kg', models.DecimalField(decimal_places=1, max_digits=6)),
                ('special_cargo', models.JSONField(blank=True, default=list, help_text='List of special-cargo codes')),
                ('sender_city', models.CharField(max_length=120)),
                ('sender_address', models.CharField(blank=True, max_length=255)),
                ('sender_name', models.CharField(max_length=120)),
                ('sender_phones', models.JSONField(default=list)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('sender_ttn', models.CharField(blank=True, max_length=60)),
                ('recipient_city', models.CharField(max_length=120)),
                ('recipient_address', models.CharField(blank=True, max_length=255)),
                ('recipient_name', models.CharField(max_length=120)),
                ('recipient_phones', models.JSONField(default=list)),
                ('promocode', models.CharField(blank=True, max_length=40)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_applications', to='core.trip')),
            ],
        ),
    ]
